name: CI Linux

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential debhelper librtlsdr-dev libusb-1.0-0-dev pkg-config fakeroot libbladerf-dev dh-systemd libhackrf-dev liblimesuite-dev
    - name: make
      run: dpkg-buildpackage -b -us -uc
    - name: test
      run: make test
