name: Mac CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        brew update
        brew install librtlsdr
        brew install libbladerf
        brew install hackrf
        brew install pkg-config
    - name: Fix headers
      run: xcode-select --install
#      find / | grep endian.h
#        sudo ln -s /usr/include/machine/endian.h /usr/include/endian.h
    - name: make
      run: make
    - name: test
      run: make test
